
package impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSOAPImpl", targetNamespace = "http://impl/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServerSOAPImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/getItemsRequest", output = "http://impl/ServerSOAPImpl/getItemsResponse")
    public String getItems();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/loginRequest", output = "http://impl/ServerSOAPImpl/loginResponse")
    public String login();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/logoutRequest", output = "http://impl/ServerSOAPImpl/logoutResponse")
    public String logout(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/addToCartRequest", output = "http://impl/ServerSOAPImpl/addToCartResponse")
    public String addToCart(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        int arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/getClientCartRequest", output = "http://impl/ServerSOAPImpl/getClientCartResponse")
    public String getClientCart(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/checkOutCartRequest", output = "http://impl/ServerSOAPImpl/checkOutCartResponse")
    public String checkOutCart(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/getItemByIdRequest", output = "http://impl/ServerSOAPImpl/getItemByIdResponse")
    public String getItemById(
        @WebParam(name = "id", partName = "id")
        int id);

}
