
package impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServerSOAPImpl", targetNamespace = "http://impl/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServerSOAPImpl {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/getItemsRequest", output = "http://impl/ServerSOAPImpl/getItemsResponse")
    public String getItems();

    /**
     * 
     * @param id
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/isItemAvailableRequest", output = "http://impl/ServerSOAPImpl/isItemAvailableResponse")
    public boolean isItemAvailable(
        @WebParam(name = "id", partName = "id")
        int id);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://impl/ServerSOAPImpl/getItemByIdRequest", output = "http://impl/ServerSOAPImpl/getItemByIdResponse")
    public String getItemById(
        @WebParam(name = "id", partName = "id")
        int id);

}
